export const PLACEHOLDER_EXERCISES = [
  { id: 1, name: "Barbell Bench Press", categories: ["Barbell"], muscle_groups: ["Chest","Triceps"] },
  { id: 2, name: "Dumbbell Bench Press", categories: ["Dumbbell"], muscle_groups: ["Chest","Triceps"] },
  { id: 3, name: "Smith Machine Bench Press", categories: ["Smith Machine"], muscle_groups: ["Chest","Triceps"] },
  { id: 4, name: "Machine Bench Press", categories: ["Machine"], muscle_groups: ["Chest","Triceps"] },
  { id: 5, name: "Barbell Squat", categories: ["Barbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 6, name: "Dumbbell Squat", categories: ["Dumbbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 7, name: "Smith Machine Squat", categories: ["Smith Machine"], muscle_groups: ["Legs","Glutes"] },
  { id: 8, name: "Machine Squat", categories: ["Machine"], muscle_groups: ["Legs","Glutes"] },
  { id: 9, name: "Barbell Deadlift", categories: ["Barbell"], muscle_groups: ["Back","Legs"] },
  { id: 10, name: "Dumbbell Deadlift", categories: ["Dumbbell"], muscle_groups: ["Back","Legs"] },
  { id: 11, name: "Trap Bar Deadlift", categories: ["Trap Bar"], muscle_groups: ["Back","Legs"] },
  { id: 12, name: "Barbell Overhead Press", categories: ["Barbell"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 13, name: "Dumbbell Overhead Press", categories: ["Dumbbell"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 14, name: "Machine Overhead Press", categories: ["Machine"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 15, name: "Barbell Bent Over Row", categories: ["Barbell"], muscle_groups: ["Back","Biceps"] },
  { id: 16, name: "Dumbbell Bent Over Row", categories: ["Dumbbell"], muscle_groups: ["Back","Biceps"] },
  { id: 17, name: "Machine Bent Over Row", categories: ["Machine"], muscle_groups: ["Back","Biceps"] },
  { id: 18, name: "Cable Bent Over Row", categories: ["Cable"], muscle_groups: ["Back","Biceps"] },
  { id: 19, name: "Barbell Bicep Curl", categories: ["Barbell"], muscle_groups: ["Biceps"] },
  { id: 20, name: "Dumbbell Bicep Curl", categories: ["Dumbbell"], muscle_groups: ["Biceps"] },
  { id: 21, name: "Cable Bicep Curl", categories: ["Cable"], muscle_groups: ["Biceps"] },
  { id: 22, name: "Resistance Band Bicep Curl", categories: ["Resistance Band"], muscle_groups: ["Biceps"] },
  { id: 23, name: "Cable Tricep Extension", categories: ["Cable"], muscle_groups: ["Triceps"] },
  { id: 24, name: "Dumbbell Tricep Extension", categories: ["Dumbbell"], muscle_groups: ["Triceps"] },
  { id: 25, name: "Resistance Band Tricep Extension", categories: ["Resistance Band"], muscle_groups: ["Triceps"] },
  { id: 26, name: "Dumbbell Lunge", categories: ["Dumbbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 27, name: "Barbell Lunge", categories: ["Barbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 28, name: "Bodyweight Lunge", categories: ["Bodyweight"], muscle_groups: ["Legs","Glutes"] },
  { id: 29, name: "Bodyweight Pull-Up", categories: ["Bodyweight"], muscle_groups: ["Back","Biceps"] },
  { id: 30, name: "Assisted Machine Pull-Up", categories: ["Assisted Machine"], muscle_groups: ["Back","Biceps"] },
  { id: 31, name: "Bodyweight Dip", categories: ["Bodyweight"], muscle_groups: ["Chest","Triceps"] },
  { id: 32, name: "Assisted Machine Dip", categories: ["Assisted Machine"], muscle_groups: ["Chest","Triceps"] },
  { id: 33, name: "Cable Chest Fly", categories: ["Cable"], muscle_groups: ["Chest"] },
  { id: 34, name: "Dumbbell Chest Fly", categories: ["Dumbbell"], muscle_groups: ["Chest"] },
  { id: 35, name: "Machine Chest Fly", categories: ["Machine"], muscle_groups: ["Chest"] },
  { id: 36, name: "Machine Leg Press", categories: ["Machine"], muscle_groups: ["Legs","Glutes"] },
  { id: 37, name: "Cable Lat Pulldown", categories: ["Cable"], muscle_groups: ["Back","Biceps"] },
  { id: 38, name: "Machine Lat Pulldown", categories: ["Machine"], muscle_groups: ["Back","Biceps"] },
  { id: 39, name: "Machine Shoulder Press", categories: ["Machine"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 40, name: "Machine Leg Curl", categories: ["Machine"], muscle_groups: ["Legs"] },
  { id: 41, name: "Machine Leg Extension", categories: ["Machine"], muscle_groups: ["Legs"] },
  { id: 42, name: "Machine Calf Raise", categories: ["Machine"], muscle_groups: ["Calves"] },
  { id: 43, name: "Dumbbell Calf Raise", categories: ["Dumbbell"], muscle_groups: ["Calves"] },
  { id: 44, name: "Bodyweight Calf Raise", categories: ["Bodyweight"], muscle_groups: ["Calves"] },
  { id: 45, name: "Bodyweight Plank", categories: ["Bodyweight"], muscle_groups: ["Core"] },
  { id: 46, name: "Bodyweight Russian Twist", categories: ["Bodyweight"], muscle_groups: ["Core"] },
  { id: 47, name: "Cable Russian Twist", categories: ["Cable"], muscle_groups: ["Core"] },
  { id: 48, name: "Bodyweight Leg Raise", categories: ["Bodyweight"], muscle_groups: ["Core","Hip Flexors"] },
  { id: 49, name: "Captain's Chair Leg Raise", categories: ["Captain's Chair"], muscle_groups: ["Core","Hip Flexors"] },
  { id: 50, name: "Barbell Bench Press Variation", categories: ["Barbell"], muscle_groups: ["Chest","Triceps"] },
  { id: 51, name: "Dumbbell Bench Press Variation", categories: ["Dumbbell"], muscle_groups: ["Chest","Triceps"] },
  { id: 52, name: "Smith Machine Bench Press Variation", categories: ["Smith Machine"], muscle_groups: ["Chest","Triceps"] },
  { id: 53, name: "Machine Bench Press Variation", categories: ["Machine"], muscle_groups: ["Chest","Triceps"] },
  { id: 54, name: "Barbell Squat Variation", categories: ["Barbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 55, name: "Dumbbell Squat Variation", categories: ["Dumbbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 56, name: "Smith Machine Squat Variation", categories: ["Smith Machine"], muscle_groups: ["Legs","Glutes"] },
  { id: 57, name: "Machine Squat Variation", categories: ["Machine"], muscle_groups: ["Legs","Glutes"] },
  { id: 58, name: "Barbell Deadlift Variation", categories: ["Barbell"], muscle_groups: ["Back","Legs"] },
  { id: 59, name: "Dumbbell Deadlift Variation", categories: ["Dumbbell"], muscle_groups: ["Back","Legs"] },
  { id: 60, name: "Trap Bar Deadlift Variation", categories: ["Trap Bar"], muscle_groups: ["Back","Legs"] },
  { id: 61, name: "Barbell Overhead Press Variation", categories: ["Barbell"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 62, name: "Dumbbell Overhead Press Variation", categories: ["Dumbbell"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 63, name: "Machine Overhead Press Variation", categories: ["Machine"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 64, name: "Barbell Bent Over Row Variation", categories: ["Barbell"], muscle_groups: ["Back","Biceps"] },
  { id: 65, name: "Dumbbell Bent Over Row Variation", categories: ["Dumbbell"], muscle_groups: ["Back","Biceps"] },
  { id: 66, name: "Machine Bent Over Row Variation", categories: ["Machine"], muscle_groups: ["Back","Biceps"] },
  { id: 67, name: "Cable Bent Over Row Variation", categories: ["Cable"], muscle_groups: ["Back","Biceps"] },
  { id: 68, name: "Barbell Bicep Curl Variation", categories: ["Barbell"], muscle_groups: ["Biceps"] },
  { id: 69, name: "Dumbbell Bicep Curl Variation", categories: ["Dumbbell"], muscle_groups: ["Biceps"] },
  { id: 70, name: "Cable Bicep Curl Variation", categories: ["Cable"], muscle_groups: ["Biceps"] },
  { id: 71, name: "Resistance Band Bicep Curl Variation", categories: ["Resistance Band"], muscle_groups: ["Biceps"] },
  { id: 72, name: "Cable Tricep Extension Variation", categories: ["Cable"], muscle_groups: ["Triceps"] },
  { id: 73, name: "Dumbbell Tricep Extension Variation", categories: ["Dumbbell"], muscle_groups: ["Triceps"] },
  { id: 74, name: "Resistance Band Tricep Extension Variation", categories: ["Resistance Band"], muscle_groups: ["Triceps"] },
  { id: 75, name: "Dumbbell Lunge Variation", categories: ["Dumbbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 76, name: "Barbell Lunge Variation", categories: ["Barbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 77, name: "Bodyweight Lunge Variation", categories: ["Bodyweight"], muscle_groups: ["Legs","Glutes"] },
  { id: 78, name: "Bodyweight Pull-Up Variation", categories: ["Bodyweight"], muscle_groups: ["Back","Biceps"] },
  { id: 79, name: "Assisted Machine Pull-Up Variation", categories: ["Assisted Machine"], muscle_groups: ["Back","Biceps"] },
  { id: 80, name: "Bodyweight Dip Variation", categories: ["Bodyweight"], muscle_groups: ["Chest","Triceps"] },
  { id: 81, name: "Assisted Machine Dip Variation", categories: ["Assisted Machine"], muscle_groups: ["Chest","Triceps"] },
  { id: 82, name: "Cable Chest Fly Variation", categories: ["Cable"], muscle_groups: ["Chest"] },
  { id: 83, name: "Dumbbell Chest Fly Variation", categories: ["Dumbbell"], muscle_groups: ["Chest"] },
  { id: 84, name: "Machine Chest Fly Variation", categories: ["Machine"], muscle_groups: ["Chest"] },
  { id: 85, name: "Machine Leg Press Variation", categories: ["Machine"], muscle_groups: ["Legs","Glutes"] },
  { id: 86, name: "Cable Lat Pulldown Variation", categories: ["Cable"], muscle_groups: ["Back","Biceps"] },
  { id: 87, name: "Machine Lat Pulldown Variation", categories: ["Machine"], muscle_groups: ["Back","Biceps"] },
  { id: 88, name: "Machine Shoulder Press Variation", categories: ["Machine"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 89, name: "Machine Leg Curl Variation", categories: ["Machine"], muscle_groups: ["Legs"] },
  { id: 90, name: "Machine Leg Extension Variation", categories: ["Machine"], muscle_groups: ["Legs"] },
  { id: 91, name: "Machine Calf Raise Variation", categories: ["Machine"], muscle_groups: ["Calves"] },
  { id: 92, name: "Dumbbell Calf Raise Variation", categories: ["Dumbbell"], muscle_groups: ["Calves"] },
  { id: 93, name: "Bodyweight Calf Raise Variation", categories: ["Bodyweight"], muscle_groups: ["Calves"] },
  { id: 94, name: "Bodyweight Plank Variation", categories: ["Bodyweight"], muscle_groups: ["Core"] },
  { id: 95, name: "Bodyweight Russian Twist Variation", categories: ["Bodyweight"], muscle_groups: ["Core"] },
  { id: 96, name: "Cable Russian Twist Variation", categories: ["Cable"], muscle_groups: ["Core"] },
  { id: 97, name: "Bodyweight Leg Raise Variation", categories: ["Bodyweight"], muscle_groups: ["Core","Hip Flexors"] },
  { id: 98, name: "Captain's Chair Leg Raise Variation", categories: ["Captain's Chair"], muscle_groups: ["Core","Hip Flexors"] },
  { id: 99, name: "Barbell Bench Press Variation", categories: ["Barbell"], muscle_groups: ["Chest","Triceps"] },
  { id: 100, name: "Dumbbell Bench Press Variation", categories: ["Dumbbell"], muscle_groups: ["Chest","Triceps"] },
  { id: 101, name: "Smith Machine Bench Press Variation", categories: ["Smith Machine"], muscle_groups: ["Chest","Triceps"] },
  { id: 102, name: "Machine Bench Press Variation", categories: ["Machine"], muscle_groups: ["Chest","Triceps"] },
  { id: 103, name: "Barbell Squat Variation", categories: ["Barbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 104, name: "Dumbbell Squat Variation", categories: ["Dumbbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 105, name: "Smith Machine Squat Variation", categories: ["Smith Machine"], muscle_groups: ["Legs","Glutes"] },
  { id: 106, name: "Machine Squat Variation", categories: ["Machine"], muscle_groups: ["Legs","Glutes"] },
  { id: 107, name: "Barbell Deadlift Variation", categories: ["Barbell"], muscle_groups: ["Back","Legs"] },
  { id: 108, name: "Dumbbell Deadlift Variation", categories: ["Dumbbell"], muscle_groups: ["Back","Legs"] },
  { id: 109, name: "Trap Bar Deadlift Variation", categories: ["Trap Bar"], muscle_groups: ["Back","Legs"] },
  { id: 110, name: "Barbell Overhead Press Variation", categories: ["Barbell"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 111, name: "Dumbbell Overhead Press Variation", categories: ["Dumbbell"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 112, name: "Machine Overhead Press Variation", categories: ["Machine"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 113, name: "Barbell Bent Over Row Variation", categories: ["Barbell"], muscle_groups: ["Back","Biceps"] },
  { id: 114, name: "Dumbbell Bent Over Row Variation", categories: ["Dumbbell"], muscle_groups: ["Back","Biceps"] },
  { id: 115, name: "Machine Bent Over Row Variation", categories: ["Machine"], muscle_groups: ["Back","Biceps"] },
  { id: 116, name: "Cable Bent Over Row Variation", categories: ["Cable"], muscle_groups: ["Back","Biceps"] },
  { id: 117, name: "Barbell Bicep Curl Variation", categories: ["Barbell"], muscle_groups: ["Biceps"] },
  { id: 118, name: "Dumbbell Bicep Curl Variation", categories: ["Dumbbell"], muscle_groups: ["Biceps"] },
  { id: 119, name: "Cable Bicep Curl Variation", categories: ["Cable"], muscle_groups: ["Biceps"] },
  { id: 120, name: "Resistance Band Bicep Curl Variation", categories: ["Resistance Band"], muscle_groups: ["Biceps"] },
  { id: 121, name: "Cable Tricep Extension Variation", categories: ["Cable"], muscle_groups: ["Triceps"] },
  { id: 122, name: "Dumbbell Tricep Extension Variation", categories: ["Dumbbell"], muscle_groups: ["Triceps"] },
  { id: 123, name: "Resistance Band Tricep Extension Variation", categories: ["Resistance Band"], muscle_groups: ["Triceps"] },
  { id: 124, name: "Dumbbell Lunge Variation", categories: ["Dumbbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 125, name: "Barbell Lunge Variation", categories: ["Barbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 126, name: "Bodyweight Lunge Variation", categories: ["Bodyweight"], muscle_groups: ["Legs","Glutes"] },
  { id: 127, name: "Bodyweight Pull-Up Variation", categories: ["Bodyweight"], muscle_groups: ["Back","Biceps"] },
  { id: 128, name: "Assisted Machine Pull-Up Variation", categories: ["Assisted Machine"], muscle_groups: ["Back","Biceps"] },
  { id: 129, name: "Bodyweight Dip Variation", categories: ["Bodyweight"], muscle_groups: ["Chest","Triceps"] },
  { id: 130, name: "Assisted Machine Dip Variation", categories: ["Assisted Machine"], muscle_groups: ["Chest","Triceps"] },
  { id: 131, name: "Cable Chest Fly Variation", categories: ["Cable"], muscle_groups: ["Chest"] },
  { id: 132, name: "Dumbbell Chest Fly Variation", categories: ["Dumbbell"], muscle_groups: ["Chest"] },
  { id: 133, name: "Machine Chest Fly Variation", categories: ["Machine"], muscle_groups: ["Chest"] },
  { id: 134, name: "Machine Leg Press Variation", categories: ["Machine"], muscle_groups: ["Legs","Glutes"] },
  { id: 135, name: "Cable Lat Pulldown Variation", categories: ["Cable"], muscle_groups: ["Back","Biceps"] },
  { id: 136, name: "Machine Lat Pulldown Variation", categories: ["Machine"], muscle_groups: ["Back","Biceps"] },
  { id: 137, name: "Machine Shoulder Press Variation", categories: ["Machine"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 138, name: "Machine Leg Curl Variation", categories: ["Machine"], muscle_groups: ["Legs"] },
  { id: 139, name: "Machine Leg Extension Variation", categories: ["Machine"], muscle_groups: ["Legs"] },
  { id: 140, name: "Machine Calf Raise Variation", categories: ["Machine"], muscle_groups: ["Calves"] },
  { id: 141, name: "Dumbbell Calf Raise Variation", categories: ["Dumbbell"], muscle_groups: ["Calves"] },
  { id: 142, name: "Bodyweight Calf Raise Variation", categories: ["Bodyweight"], muscle_groups: ["Calves"] },
  { id: 143, name: "Bodyweight Plank Variation", categories: ["Bodyweight"], muscle_groups: ["Core"] },
  { id: 144, name: "Bodyweight Russian Twist Variation", categories: ["Bodyweight"], muscle_groups: ["Core"] },
  { id: 145, name: "Cable Russian Twist Variation", categories: ["Cable"], muscle_groups: ["Core"] },
  { id: 146, name: "Bodyweight Leg Raise Variation", categories: ["Bodyweight"], muscle_groups: ["Core","Hip Flexors"] },
  { id: 147, name: "Captain's Chair Leg Raise Variation", categories: ["Captain's Chair"], muscle_groups: ["Core","Hip Flexors"] },
  { id: 148, name: "Barbell Bench Press Variation Variation", categories: ["Barbell"], muscle_groups: ["Chest","Triceps"] },
  { id: 149, name: "Dumbbell Bench Press Variation Variation", categories: ["Dumbbell"], muscle_groups: ["Chest","Triceps"] },
  { id: 150, name: "Smith Machine Bench Press Variation Variation", categories: ["Smith Machine"], muscle_groups: ["Chest","Triceps"] },
  { id: 151, name: "Machine Bench Press Variation Variation", categories: ["Machine"], muscle_groups: ["Chest","Triceps"] },
  { id: 152, name: "Barbell Squat Variation Variation", categories: ["Barbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 153, name: "Dumbbell Squat Variation Variation", categories: ["Dumbbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 154, name: "Smith Machine Squat Variation Variation", categories: ["Smith Machine"], muscle_groups: ["Legs","Glutes"] },
  { id: 155, name: "Machine Squat Variation Variation", categories: ["Machine"], muscle_groups: ["Legs","Glutes"] },
  { id: 156, name: "Barbell Deadlift Variation Variation", categories: ["Barbell"], muscle_groups: ["Back","Legs"] },
  { id: 157, name: "Dumbbell Deadlift Variation Variation", categories: ["Dumbbell"], muscle_groups: ["Back","Legs"] },
  { id: 158, name: "Trap Bar Deadlift Variation Variation", categories: ["Trap Bar"], muscle_groups: ["Back","Legs"] },
  { id: 159, name: "Barbell Overhead Press Variation Variation", categories: ["Barbell"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 160, name: "Dumbbell Overhead Press Variation Variation", categories: ["Dumbbell"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 161, name: "Machine Overhead Press Variation Variation", categories: ["Machine"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 162, name: "Barbell Bent Over Row Variation Variation", categories: ["Barbell"], muscle_groups: ["Back","Biceps"] },
  { id: 163, name: "Dumbbell Bent Over Row Variation Variation", categories: ["Dumbbell"], muscle_groups: ["Back","Biceps"] },
  { id: 164, name: "Machine Bent Over Row Variation Variation", categories: ["Machine"], muscle_groups: ["Back","Biceps"] },
  { id: 165, name: "Cable Bent Over Row Variation Variation", categories: ["Cable"], muscle_groups: ["Back","Biceps"] },
  { id: 166, name: "Barbell Bicep Curl Variation Variation", categories: ["Barbell"], muscle_groups: ["Biceps"] },
  { id: 167, name: "Dumbbell Bicep Curl Variation Variation", categories: ["Dumbbell"], muscle_groups: ["Biceps"] },
  { id: 168, name: "Cable Bicep Curl Variation Variation", categories: ["Cable"], muscle_groups: ["Biceps"] },
  { id: 169, name: "Resistance Band Bicep Curl Variation Variation", categories: ["Resistance Band"], muscle_groups: ["Biceps"] },
  { id: 170, name: "Cable Tricep Extension Variation Variation", categories: ["Cable"], muscle_groups: ["Triceps"] },
  { id: 171, name: "Dumbbell Tricep Extension Variation Variation", categories: ["Dumbbell"], muscle_groups: ["Triceps"] },
  { id: 172, name: "Resistance Band Tricep Extension Variation Variation", categories: ["Resistance Band"], muscle_groups: ["Triceps"] },
  { id: 173, name: "Dumbbell Lunge Variation Variation", categories: ["Dumbbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 174, name: "Barbell Lunge Variation Variation", categories: ["Barbell"], muscle_groups: ["Legs","Glutes"] },
  { id: 175, name: "Bodyweight Lunge Variation Variation", categories: ["Bodyweight"], muscle_groups: ["Legs","Glutes"] },
  { id: 176, name: "Bodyweight Pull-Up Variation Variation", categories: ["Bodyweight"], muscle_groups: ["Back","Biceps"] },
  { id: 177, name: "Assisted Machine Pull-Up Variation Variation", categories: ["Assisted Machine"], muscle_groups: ["Back","Biceps"] },
  { id: 178, name: "Bodyweight Dip Variation Variation", categories: ["Bodyweight"], muscle_groups: ["Chest","Triceps"] },
  { id: 179, name: "Assisted Machine Dip Variation Variation", categories: ["Assisted Machine"], muscle_groups: ["Chest","Triceps"] },
  { id: 180, name: "Cable Chest Fly Variation Variation", categories: ["Cable"], muscle_groups: ["Chest"] },
  { id: 181, name: "Dumbbell Chest Fly Variation Variation", categories: ["Dumbbell"], muscle_groups: ["Chest"] },
  { id: 182, name: "Machine Chest Fly Variation Variation", categories: ["Machine"], muscle_groups: ["Chest"] },
  { id: 183, name: "Machine Leg Press Variation Variation", categories: ["Machine"], muscle_groups: ["Legs","Glutes"] },
  { id: 184, name: "Cable Lat Pulldown Variation Variation", categories: ["Cable"], muscle_groups: ["Back","Biceps"] },
  { id: 185, name: "Machine Lat Pulldown Variation Variation", categories: ["Machine"], muscle_groups: ["Back","Biceps"] },
  { id: 186, name: "Machine Shoulder Press Variation Variation", categories: ["Machine"], muscle_groups: ["Shoulders","Triceps"] },
  { id: 187, name: "Machine Leg Curl Variation Variation", categories: ["Machine"], muscle_groups: ["Legs"] },
  { id: 188, name: "Machine Leg Extension Variation Variation", categories: ["Machine"], muscle_groups: ["Legs"] },
  { id: 189, name: "Machine Calf Raise Variation Variation", categories: ["Machine"], muscle_groups: ["Calves"] },
  { id: 190, name: "Dumbbell Calf Raise Variation Variation", categories: ["Dumbbell"], muscle_groups: ["Calves"] },
  { id: 191, name: "Bodyweight Calf Raise Variation Variation", categories: ["Bodyweight"], muscle_groups: ["Calves"] },
  { id: 192, name: "Bodyweight Plank Variation Variation", categories: ["Bodyweight"], muscle_groups: ["Core"] },
  { id: 193, name: "Bodyweight Russian Twist Variation Variation", categories: ["Bodyweight"], muscle_groups: ["Core"] },
  { id: 194, name: "Cable Russian Twist Variation Variation", categories: ["Cable"], muscle_groups: ["Core"] },
  { id: 195, name: "Bodyweight Leg Raise Variation Variation", categories: ["Bodyweight"], muscle_groups: ["Core","Hip Flexors"] },
  { id: 196, name: "Captain's Chair Leg Raise Variation Variation", categories: ["Captain's Chair"], muscle_groups: ["Core","Hip Flexors"] },
  { id: 197, name: "Barbell Bench Press Variation", categories: ["Barbell"], muscle_groups: ["Chest","Triceps"] },
  { id: 198, name: "Dumbbell Bench Press Variation", categories: ["Dumbbell"], muscle_groups: ["Chest","Triceps"] },
  { id: 199, name: "Smith Machine Bench Press Variation", categories: ["Smith Machine"], muscle_groups: ["Chest","Triceps"] },
  { id: 200, name: "Machine Bench Press Variation", categories: ["Machine"], muscle_groups: ["Chest","Triceps"] },
];